import { createSlice } from '@reduxjs/toolkit';

// Initialize language from localStorage or default to 'en'
const getInitialLanguage = () => {
  const savedLanguage = localStorage.getItem('language');
  if (savedLanguage) {
    return savedLanguage;
  }
  return 'en';
};

// Функция для добавления недостающих переводов
const addMissingTranslations = (translations) => {
  // Добавляем перевод для "Admin Panel" если он отсутствует
  if (!translations.en.adminPanel) {
    translations.en.adminPanel = 'Admin Panel';
    translations.ru.adminPanel = 'Админ-панель';
    translations.kz.adminPanel = 'Әкімшілік панелі';
  }
  
  // Добавляем перевод для "Account Settings" если он отсутствует
  if (!translations.en.accountSettings) {
    translations.en.accountSettings = 'Account Settings';
    translations.ru.accountSettings = 'Настройки аккаунта';
    translations.kz.accountSettings = 'Аккаунт параметрлері';
  }
  
  // Добавляем переводы для статистики админ-панели
  translations.en.categoriesStats = 'Categories Stats';
  translations.ru.categoriesStats = 'Статистика категорий';
  translations.kz.categoriesStats = 'Санаттар статистикасы';
  
  translations.en.viewAll = 'View all';
  translations.ru.viewAll = 'Смотреть все';
  translations.kz.viewAll = 'Барлығын көру';
  
  translations.en.details = 'View details';
  translations.ru.details = 'Подробнее';
  translations.kz.details = 'Толығырақ';
  
  translations.en.noData = 'No data available';
  translations.ru.noData = 'Данные отсутствуют';
  translations.kz.noData = 'Деректер жоқ';
  
  translations.en.categoriesDistribution = 'Categories Distribution';
  translations.ru.categoriesDistribution = 'Распределение по категориям';
  translations.kz.categoriesDistribution = 'Санаттар бойынша бөлу';
  
  translations.en.userRegistrationStats = 'User Registration Statistics';
  translations.ru.userRegistrationStats = 'Статистика регистрации пользователей';
  translations.kz.userRegistrationStats = 'Пайдаланушыларды тіркеу статистикасы';
  
  return translations;
};

const languageSlice = createSlice({
  name: 'language',
  initialState: {
    current: getInitialLanguage(),
    translations: addMissingTranslations({
      en: {
        home: 'Home',
        places: 'Places',
        contacts: 'Contacts',
        login: 'Login',
        register: 'Register',
        profile: 'Profile',
        logout: 'Logout',
        admin: 'Admin',
        search: 'Search places...',
        allCategories: 'All Categories',
        parks: 'Parks',
        cafes: 'Cafes',
        hotels: 'Hotels',
        museums: 'Museums',
        nature: 'Nature',
        shopping: 'Shopping',
        findPerfectPlace: 'Find Your Perfect Place',
        discoverBestLocations: 'Discover the best locations around you',
        popularPlaces: 'Popular Places',
        contactUs: 'Contact Us',
        getInTouch: 'Get in Touch',
        contactDescription: 'Have questions about our service? Want to provide feedback? Our team is here to help!',
        address: 'Address',
        phone: 'Phone',
        email: 'Email',
        sendMessage: 'Send a Message',
        name: 'Name',
        yourName: 'Your name',
        yourEmail: 'Your email',
        message: 'Message',
        yourMessage: 'Your message',
        send: 'Send Message',
        ourHours: 'Our Hours',
        mondayFriday: 'Monday - Friday',
        saturday: 'Saturday',
        sunday: 'Sunday',
        closed: 'Closed',
        // Login and Register form translations
        password: 'Password',
        confirmPassword: 'Confirm Password',
        username: 'Username',
        loginWelcomeBack: 'Welcome back! Please enter your details.',
        rememberMe: 'Remember me',
        forgotPassword: 'Forgot password?',
        dontHaveAccount: 'Don\'t have an account?',
        alreadyHaveAccount: 'Already have an account?',
        createAccount: 'Create your account to get started',
        next: 'Next',
        back: 'Back',
        loggingIn: 'Signing in...',
        registering: 'Creating account...',
        agreeToTerms: 'I agree to the Terms of Service and Privacy Policy',
        // Admin panel translations
        dashboard: 'Dashboard',
        users: 'Users',
        settings: 'Settings',
        adminWelcome: 'Welcome to the admin panel. Manage places, users, and more.',
        managePlaces: 'Manage Places',
        manageUsers: 'Manage Users',
        addNewPlace: 'Add New Place',
        totalPlaces: 'Total Places',
        totalUsers: 'Total Users',
        totalReviews: 'Total Reviews',
        totalFavorites: 'Total Favorites',
        averageRating: 'Average Rating',
        userRegistrationStats: 'User Registration Stats',
        pendingApprovals: 'Pending Approvals',
        category: 'Category',
        status: 'Status',
        actions: 'Actions',
        approve: 'Approve',
        delete: 'Delete',
        active: 'Active',
        pending: 'Pending',
        makeAdmin: 'Make Admin',
        user: 'User',
        role: 'Role',
        applicationSettings: 'Application Settings',
        siteName: 'Site Name',
        siteDescription: 'Site Description',
        enableRegistration: 'Enable User Registration',
        enableRegistrationDesc: 'Allow new users to register on the site',
        saveSettings: 'Save Settings',
        allRightsReserved: 'All rights reserved.',
        block: 'Block',
        unblock: 'Unblock',
        blockedAccount: 'This account has been blocked',
        userDeleted: 'User deleted successfully',
        userBlocked: 'User blocked successfully',
        userUnblocked: 'User unblocked successfully',
        cannotBlockAdmin: 'Cannot block administrator accounts',
        cannotDeleteAdmin: 'Cannot delete administrator accounts',
        confirmDelete: 'Are you sure you want to delete this user?',
        confirmBlock: 'Are you sure you want to block this user?',
        confirmUnblock: 'Are you sure you want to unblock this user?',
        // Profile page translations
        accountInformation: 'Account Information',
        editProfile: 'Edit Profile',
        changePassword: 'Change Password',
        currentPassword: 'Current Password',
        newPassword: 'New Password',
        profileUpdated: 'Profile updated successfully',
        errorUpdatingProfile: 'Error updating profile',
        passwordUpdated: 'Password updated successfully',
        errorUpdatingPassword: 'Error updating password',
        passwordsDoNotMatch: 'Passwords do not match',
        passwordTooShort: 'Password must be at least 6 characters',
        incorrectPassword: 'Current password is incorrect',
        emailInUse: 'Email is already in use',
        cancel: 'Cancel',
        save: 'Save',
        saving: 'Saving...',
        savePassword: 'Save Password',
        profilePicture: 'Profile Picture',
        uploadPhoto: 'Upload Photo',
        dateJoined: 'Date Joined',
        // Home page translations
        topRated: 'Top Rated',
        alphabetical: 'A-Z',
        readyToExplore: 'Ready to explore more places?',
        joinCommunity: 'Join our community and discover the best locations around the world.',
        noPlacesFound: 'No places found',
        tryDifferentSearch: 'Try a different search term or category',
        // Place detail translations
        information: 'Information',
        about: 'About',
        writeReview: 'Write a Review',
        shareYourExperience: 'Share your experience',
        comment: 'Comment',
        submitReview: 'Submit Review',
        submittingReview: 'Submitting Review...',
        pleaseEnterName: 'Please enter your name',
        pleaseEnterComment: 'Please enter your comment',
        noReviewsYet: 'No reviews yet. Be the first to leave a review!',
        placeNotFound: 'Place not found',
        backToPlaces: 'Back to places',
        removeFromFavorites: 'Remove from Favorites',
        addedToFavorites: 'Added to favorites',
        removedFromFavorites: 'Removed from favorites',
        alreadyInFavorites: 'This place is already in your favorites',
        mustBeLoggedInToFavorite: 'You must be logged in to add favorites',
        mustBeLoggedInToReview: 'You must be logged in to leave a review',
        reviewAdded: 'Review added successfully',
        alreadyReviewed: 'You have already reviewed this place',
        ratingRequired: 'Rating is required',
        // Places list translations
        discoverPlaces: 'Discover Amazing Places',
        allPlaces: 'All Places',
        addPlace: 'Add Place',
        addingPlace: 'Adding Place...',
        placeAdded: 'Place added successfully',
        favorites: 'Favorites',
        fieldRequired: 'Field is required',
        atLeastOneImageRequired: 'At least one image is required',
        description: 'Description',
        location: 'Location (City, Country)',
        images: 'Images',
        atLeastOne: 'at least one',
        imageUrl: 'Image URL',
        add: 'Add',
        hours: 'Opening Hours',
        website: 'Website',
        inFavorites: 'In Favorites',
        rating: 'Rating',
        filterBy: 'Filter By',
        sortBy: 'Sort By',
        noFavoritesYet: 'You have no favorite places yet',
        exploreAndAdd: 'Explore places and add them to your favorites',
        language: 'Language',
        personalDetails: 'Personal Details',
        accountSettings: 'Account Settings',
        enterUsername: 'Enter username',
        enterEmail: 'Enter email',
        enterCurrentPassword: 'Enter current password',
        enterNewPassword: 'Enter new password',
        confirmNewPassword: 'Confirm new password',
        updatePassword: 'Update Password',
        saveChanges: 'Save Changes',
        viewAllPlaces: 'View All Places',
        exploreAll: 'Explore All Places',
        passwordRequirements: 'Password requirements:',
        minChars: 'Minimum 8 characters',
        upperCase: 'At least one uppercase letter',
        lowerCase: 'At least one lowercase letter',
        number: 'At least one number',
        specialChar: 'At least one special character (!@#$%^&*(),.?":{}|<>)',
        passwordError: 'Password does not meet requirements',
        passwordChanged: 'Password successfully changed',
        personalInfo: 'Personal Information',
        securitySettings: 'Security Settings',
      },
      ru: {
        home: 'Главная',
        places: 'Места',
        contacts: 'Контакты',
        login: 'Вход',
        register: 'Регистрация',
        profile: 'Профиль',
        logout: 'Выход',
        admin: 'Админ',
        search: 'Поиск мест...',
        allCategories: 'Все категории',
        parks: 'Парки',
        cafes: 'Кафе',
        hotels: 'Отели',
        museums: 'Музеи',
        nature: 'Природа',
        shopping: 'Шоппинг',
        findPerfectPlace: 'Найдите идеальное место',
        discoverBestLocations: 'Откройте для себя лучшие места поблизости',
        popularPlaces: 'Популярные места',
        contactUs: 'Связаться с нами',
        getInTouch: 'Свяжитесь с нами',
        contactDescription: 'Есть вопросы о нашем сервисе? Хотите оставить отзыв? Наша команда готова помочь!',
        address: 'Адрес',
        phone: 'Телефон',
        email: 'Эл. почта',
        sendMessage: 'Отправить сообщение',
        name: 'Имя',
        yourName: 'Ваше имя',
        yourEmail: 'Ваш email',
        message: 'Сообщение',
        yourMessage: 'Ваше сообщение',
        send: 'Отправить',
        ourHours: 'Часы работы',
        mondayFriday: 'Понедельник - Пятница',
        saturday: 'Суббота',
        sunday: 'Воскресенье',
        closed: 'Закрыто',
        // Login and Register form translations
        password: 'Пароль',
        confirmPassword: 'Подтвердите пароль',
        username: 'Имя пользователя',
        loginWelcomeBack: 'С возвращением! Пожалуйста, введите свои данные.',
        rememberMe: 'Запомнить меня',
        forgotPassword: 'Забыли пароль?',
        dontHaveAccount: 'Нет аккаунта?',
        alreadyHaveAccount: 'Уже есть аккаунт?',
        createAccount: 'Создайте свой аккаунт, чтобы начать',
        next: 'Далее',
        back: 'Назад',
        loggingIn: 'Вход...',
        registering: 'Создание аккаунта...',
        agreeToTerms: 'Я согласен с Условиями использования и Политикой конфиденциальности',
        // Admin panel translations
        dashboard: 'Панель управления',
        users: 'Пользователи',
        settings: 'Настройки',
        adminWelcome: 'Добро пожаловать в панель администратора. Управляйте местами, пользователями и прочим.',
        managePlaces: 'Управление местами',
        manageUsers: 'Управление пользователями',
        addNewPlace: 'Добавить место',
        totalPlaces: 'Всего мест',
        totalUsers: 'Всего пользователей',
        totalReviews: 'Всего отзывов',
        totalFavorites: 'Всего в избранном',
        averageRating: 'Средний рейтинг',
        userRegistrationStats: 'Статистика регистраций',
        pendingApprovals: 'Ожидают подтверждения',
        category: 'Категория',
        status: 'Статус',
        actions: 'Действия',
        approve: 'Подтвердить',
        delete: 'Удалить',
        active: 'Активный',
        pending: 'Ожидает',
        makeAdmin: 'Сделать админом',
        user: 'Пользователь',
        role: 'Роль',
        applicationSettings: 'Настройки приложения',
        siteName: 'Название сайта',
        siteDescription: 'Описание сайта',
        enableRegistration: 'Включить регистрацию',
        enableRegistrationDesc: 'Разрешить новым пользователям регистрироваться на сайте',
        saveSettings: 'Сохранить настройки',
        allRightsReserved: 'Все права защищены.',
        block: 'Блокировать',
        unblock: 'Разблокировать',
        blockedAccount: 'Этот аккаунт заблокирован',
        userDeleted: 'Пользователь успешно удален',
        userBlocked: 'Пользователь успешно заблокирован',
        userUnblocked: 'Пользователь успешно разблокирован',
        cannotBlockAdmin: 'Невозможно заблокировать учетные записи администраторов',
        cannotDeleteAdmin: 'Невозможно удалить учетные записи администраторов',
        confirmDelete: 'Вы уверены, что хотите удалить этого пользователя?',
        confirmBlock: 'Вы уверены, что хотите заблокировать этого пользователя?',
        confirmUnblock: 'Вы уверены, что хотите разблокировать этого пользователя?',
        // Profile page translations
        accountInformation: 'Информация об аккаунте',
        editProfile: 'Редактировать профиль',
        changePassword: 'Изменить пароль',
        currentPassword: 'Текущий пароль',
        newPassword: 'Новый пароль',
        profileUpdated: 'Профиль успешно обновлен',
        errorUpdatingProfile: 'Ошибка при обновлении профиля',
        passwordUpdated: 'Пароль успешно обновлен',
        errorUpdatingPassword: 'Ошибка при обновлении пароля',
        passwordsDoNotMatch: 'Пароли не совпадают',
        passwordTooShort: 'Пароль должен содержать не менее 6 символов',
        incorrectPassword: 'Неверный текущий пароль',
        emailInUse: 'Этот email уже используется',
        cancel: 'Отмена',
        save: 'Сохранить',
        saving: 'Сохранение...',
        savePassword: 'Сохранить пароль',
        profilePicture: 'Фото профиля',
        uploadPhoto: 'Загрузить фото',
        dateJoined: 'Дата регистрации',
        // Home page translations
        topRated: 'Лучший рейтинг',
        alphabetical: 'А-Я',
        readyToExplore: 'Готовы исследовать больше мест?',
        joinCommunity: 'Присоединяйтесь к нашему сообществу и открывайте для себя лучшие места по всему миру.',
        noPlacesFound: 'Места не найдены',
        tryDifferentSearch: 'Попробуйте другой поисковый запрос или категорию',
        // Place detail translations
        information: 'Информация',
        about: 'Описание',
        writeReview: 'Написать отзыв',
        shareYourExperience: 'Поделитесь своим опытом',
        comment: 'Комментарий',
        submitReview: 'Отправить отзыв',
        submittingReview: 'Отправка отзыва...',
        pleaseEnterName: 'Пожалуйста, введите ваше имя',
        pleaseEnterComment: 'Пожалуйста, введите комментарий',
        noReviewsYet: 'Пока нет отзывов. Будьте первым, кто оставит отзыв!',
        placeNotFound: 'Место не найдено',
        backToPlaces: 'Вернуться к местам',
        removeFromFavorites: 'Удалить из избранного',
        addedToFavorites: 'Добавлено в избранное',
        removedFromFavorites: 'Удалено из избранного',
        alreadyInFavorites: 'Это место уже в избранном',
        mustBeLoggedInToFavorite: 'Необходимо войти в систему, чтобы добавить в избранное',
        mustBeLoggedInToReview: 'Необходимо войти в систему, чтобы оставить отзыв',
        reviewAdded: 'Отзыв успешно добавлен',
        alreadyReviewed: 'Вы уже оставили отзыв для этого места',
        ratingRequired: 'Необходимо указать рейтинг',
        // Places list translations
        discoverPlaces: 'Откройте для себя удивительные места',
        allPlaces: 'Все места',
        addPlace: 'Добавить место',
        addingPlace: 'Добавление места...',
        placeAdded: 'Место успешно добавлено',
        favorites: 'Избранное',
        fieldRequired: 'Поле обязательно для заполнения',
        atLeastOneImageRequired: 'Требуется хотя бы одно изображение',
        description: 'Описание',
        location: 'Местоположение (Город, Страна)',
        images: 'Изображения',
        atLeastOne: 'минимум одно',
        imageUrl: 'URL изображения',
        add: 'Добавить',
        hours: 'Часы работы',
        website: 'Веб-сайт',
        inFavorites: 'В избранном',
        rating: 'Рейтинг',
        filterBy: 'Фильтр',
        sortBy: 'Сортировка',
        noFavoritesYet: 'У вас пока нет избранных мест',
        exploreAndAdd: 'Исследуйте места и добавляйте их в избранное',
        language: 'Язык',
        personalDetails: 'Личные данные',
        accountSettings: 'Настройки аккаунта',
        enterUsername: 'Введите имя пользователя',
        enterEmail: 'Введите email',
        enterCurrentPassword: 'Введите текущий пароль',
        enterNewPassword: 'Введите новый пароль',
        confirmNewPassword: 'Подтвердите новый пароль',
        updatePassword: 'Обновить пароль',
        saveChanges: 'Сохранить изменения',
        viewAllPlaces: 'Посмотреть все места',
        exploreAll: 'Исследовать все места',
        passwordRequirements: 'Требования к паролю:',
        minChars: 'Минимум 8 символов',
        upperCase: 'Хотя бы одна заглавная буква',
        lowerCase: 'Хотя бы одна строчная буква',
        number: 'Хотя бы одна цифра',
        specialChar: 'Хотя бы один специальный символ (!@#$%^&*(),.?":{}|<>)',
        passwordError: 'Пароль не соответствует требованиям',
        passwordChanged: 'Пароль успешно изменен',
        personalInfo: 'Личная информация',
        securitySettings: 'Настройки безопасности',
      },
      kz: {
        home: 'Басты',
        places: 'Орындар',
        contacts: 'Байланыс',
        login: 'Кіру',
        register: 'Тіркелу',
        profile: 'Профиль',
        logout: 'Шығу',
        admin: 'Әкімші',
        search: 'Орындарды іздеу...',
        allCategories: 'Барлық санаттар',
        parks: 'Саябақтар',
        cafes: 'Кафелер',
        hotels: 'Қонақ үйлер',
        museums: 'Мұражайлар',
        nature: 'Табиғат',
        shopping: 'Сауда',
        findPerfectPlace: 'Тамаша орын табыңыз',
        discoverBestLocations: 'Айналаңыздағы ең жақсы орындарды ашыңыз',
        popularPlaces: 'Танымал орындар',
        contactUs: 'Байланыс',
        getInTouch: 'Бізбен байланысыңыз',
        contactDescription: 'Біздің қызмет туралы сұрақтарыңыз бар ма? Пікір қалдырғыңыз келе ме? Біздің команда көмектесуге дайын!',
        address: 'Мекенжай',
        phone: 'Телефон',
        email: 'Электрондық пошта',
        sendMessage: 'Хабарлама жіберу',
        name: 'Аты',
        yourName: 'Сіздің атыңыз',
        yourEmail: 'Сіздің email',
        message: 'Хабарлама',
        yourMessage: 'Сіздің хабарламаңыз',
        send: 'Жіберу',
        ourHours: 'Жұмыс уақыты',
        mondayFriday: 'Дүйсенбі - Жұма',
        saturday: 'Сенбі',
        sunday: 'Жексенбі',
        closed: 'Жабық',
        // Login and Register form translations
        password: 'Құпия сөз',
        confirmPassword: 'Құпия сөзді растау',
        username: 'Пайдаланушы аты',
        loginWelcomeBack: 'Қайта қош келдіңіз! Мәліметтеріңізді енгізіңіз.',
        rememberMe: 'Мені есте сақтау',
        forgotPassword: 'Құпия сөзді ұмыттыңыз ба?',
        dontHaveAccount: 'Аккаунтыңыз жоқ па?',
        alreadyHaveAccount: 'Аккаунтыңыз бар ма?',
        createAccount: 'Бастау үшін аккаунт жасаңыз',
        next: 'Келесі',
        back: 'Артқа',
        loggingIn: 'Кіру...',
        registering: 'Аккаунт жасау...',
        agreeToTerms: 'Мен Қызмет көрсету шарттары мен Құпиялық саясатына келісемін',
        // Admin panel translations
        dashboard: 'Басқару тақтасы',
        users: 'Пайдаланушылар',
        settings: 'Параметрлер',
        adminWelcome: 'Әкімші тақтасына қош келдіңіз. Орындарды, пайдаланушыларды және т.б. басқарыңыз.',
        managePlaces: 'Орындарды басқару',
        manageUsers: 'Пайдаланушыларды басқару',
        addNewPlace: 'Орын қосу',
        totalPlaces: 'Барлық орындар',
        totalUsers: 'Барлық пайдаланушылар',
        totalReviews: 'Барлық пікірлер',
        totalFavorites: 'Барлық таңдаулылар',
        averageRating: 'Орташа рейтинг',
        userRegistrationStats: 'Тіркелу статистикасы',
        pendingApprovals: 'Күтілетін мақұлдаулар',
        category: 'Санат',
        status: 'Күйі',
        actions: 'Әрекеттер',
        approve: 'Мақұлдау',
        delete: 'Жою',
        active: 'Белсенді',
        pending: 'Күтуде',
        makeAdmin: 'Әкімші ету',
        user: 'Пайдаланушы',
        role: 'Рөлі',
        applicationSettings: 'Қолданба параметрлері',
        siteName: 'Сайт атауы',
        siteDescription: 'Сайт сипаттамасы',
        enableRegistration: 'Тіркелуді қосу',
        enableRegistrationDesc: 'Жаңа пайдаланушыларға сайтта тіркелуге рұқсат ету',
        saveSettings: 'Параметрлерді сақтау',
        allRightsReserved: 'Барлық құқықтар қорғалған.',
        block: 'Бұғаттау',
        unblock: 'Бұғаттаудан шығару',
        blockedAccount: 'Бұл аккаунт бұғатталған',
        userDeleted: 'Пайдаланушы сәтті жойылды',
        userBlocked: 'Пайдаланушы сәтті бұғатталды',
        userUnblocked: 'Пайдаланушы бұғаттаудан сәтті шығарылды',
        cannotBlockAdmin: 'Әкімші аккаунттарын бұғаттау мүмкін емес',
        cannotDeleteAdmin: 'Әкімші аккаунттарын жою мүмкін емес',
        confirmDelete: 'Бұл пайдаланушыны жойғыңыз келе ме?',
        confirmBlock: 'Бұл пайдаланушыны бұғаттағыңыз келе ме?',
        confirmUnblock: 'Бұл пайдаланушыны бұғаттаудан шығарғыңыз келе ме?',
        // Profile page translations
        accountInformation: 'Аккаунт туралы ақпарат',
        editProfile: 'Профильді өңдеу',
        changePassword: 'Құпия сөзді өзгерту',
        currentPassword: 'Ағымдағы құпия сөз',
        newPassword: 'Жаңа құпия сөз',
        profileUpdated: 'Профиль сәтті жаңартылды',
        errorUpdatingProfile: 'Профильді жаңарту кезінде қате',
        passwordUpdated: 'Құпия сөз сәтті жаңартылды',
        errorUpdatingPassword: 'Құпия сөзді жаңарту кезінде қате',
        passwordsDoNotMatch: 'Құпия сөздер сәйкес келмейді',
        passwordTooShort: 'Құпия сөз кемінде 6 таңбадан тұруы керек',
        incorrectPassword: 'Ағымдағы құпия сөз дұрыс емес',
        emailInUse: 'Бұл email қазірдің өзінде қолданыста',
        cancel: 'Болдырмау',
        save: 'Сақтау',
        saving: 'Сақтау...',
        savePassword: 'Құпия сөзді сақтау',
        profilePicture: 'Профиль суреті',
        uploadPhoto: 'Сурет жүктеу',
        dateJoined: 'Тіркелген күні',
        // Home page translations
        topRated: 'Үздік бағаланған',
        alphabetical: 'А-Я',
        readyToExplore: 'Көбірек жерлерді зерттеуге дайынсыз ба?',
        joinCommunity: 'Біздің қауымдастыққа қосылыңыз және әлемдегі ең жақсы орындарды табыңыз.',
        noPlacesFound: 'Орындар табылмады',
        tryDifferentSearch: 'Басқа іздеу сұрауын немесе санатты көріңіз',
        // Place detail translations
        information: 'Ақпарат',
        about: 'Сипаттама',
        writeReview: 'Написать отзыв',
        shareYourExperience: 'Тәжірибеңізбен бөлісіңіз',
        comment: 'Пікір',
        submitReview: 'Пікір жіберу',
        submittingReview: 'Пікір жіберу...',
        pleaseEnterName: 'Атыңызды енгізіңіз',
        pleaseEnterComment: 'Пікіріңізді енгізіңіз',
        noReviewsYet: 'Әлі пікірлер жоқ. Пікір қалдырған алғашқы адам болыңыз!',
        placeNotFound: 'Орын табылмады',
        backToPlaces: 'Орындарға оралу',
        removeFromFavorites: 'Удалить из избранного',
        addedToFavorites: 'Таңдаулыларға қосылды',
        removedFromFavorites: 'Таңдаулылардан алынды',
        alreadyInFavorites: 'Бұл орын таңдаулыларда',
        mustBeLoggedInToFavorite: 'Таңдаулыларға қосу үшін жүйеге кіру керек',
        mustBeLoggedInToReview: 'Пікір қалдыру үшін жүйеге кіру керек',
        reviewAdded: 'Пікір сәтті қосылды',
        alreadyReviewed: 'Сіз бұл орынға әлдеқашан пікір қалдырдыңыз',
        ratingRequired: 'Рейтингті көрсету қажет',
        // Places list translations
        discoverPlaces: 'Тамаша орындарды ашыңыз',
        allPlaces: 'Барлық орындар',
        addPlace: 'Орын қосу',
        addingPlace: 'Орын қосу...',
        placeAdded: 'Орын сәтті қосылды',
        favorites: 'Таңдаулылар',
        fieldRequired: 'Өріс толтырылуы қажет',
        atLeastOneImageRequired: 'Кем дегенде бір сурет қажет',
        description: 'Сипаттама',
        location: 'Орналасқан жері (Қала, Ел)',
        images: 'Суреттер',
        atLeastOne: 'кем дегенде біреу',
        imageUrl: 'Сурет URL',
        add: 'Қосу',
        hours: 'Жұмыс уақыты',
        website: 'Веб-сайт',
        inFavorites: 'Таңдаулыларда',
        rating: 'Рейтинг',
        filterBy: 'Сүзгі',
        sortBy: 'Сұрыптау',
        noFavoritesYet: 'Сізде әлі таңдаулы орындар жоқ',
        exploreAndAdd: 'Орындарды зерттеп, оларды таңдаулыларға қосыңыз',
        language: 'Тіл',
        personalDetails: 'Жеке деректер',
        accountSettings: 'Аккаунт параметрлері',
        enterUsername: 'Пайдаланушы атын енгізіңіз',
        enterEmail: 'Email енгізіңіз',
        enterCurrentPassword: 'Ағымдағы құпия сөзді енгізіңіз',
        enterNewPassword: 'Жаңа құпия сөзді енгізіңіз',
        confirmNewPassword: 'Жаңа құпия сөзді растаңыз',
        updatePassword: 'Құпия сөзді жаңарту',
        saveChanges: 'Өзгерістерді сақтау',
        viewAllPlaces: 'Барлық орындарды көру',
        exploreAll: 'Барлық орындарды зерттеу',
        passwordRequirements: 'Құпия сөзге қойылатын талаптар:',
        minChars: 'Кемінде 8 таңба',
        upperCase: 'Кемінде бір бас әріп',
        lowerCase: 'Кемінде бір кіші әріп',
        number: 'Кемінде бір сан',
        specialChar: 'Кемінде бір арнайы таңба (!@#$%^&*(),.?":{}|<>)',
        passwordError: 'Құпия сөз талаптарға сәйкес келмейді',
        passwordChanged: 'Құпия сөз сәтті өзгертілді',
        personalInfo: 'Жеке ақпарат',
        securitySettings: 'Қауіпсіздік параметрлері',
      }
    })
  },
  reducers: {
    setLanguage: (state, action) => {
      state.current = action.payload;
      localStorage.setItem('language', action.payload);
    },
  },
});

export const { setLanguage } = languageSlice.actions;
export const selectTranslation = (state) => 
  state.language.translations[state.language.current] || state.language.translations.en;
  
export default languageSlice.reducer; 